### ISSUE TITLE
Resource leak

### ISSUE THREAD

**Issue by QiAnXinCodeSafe** [IBM/mini-era#12]
Stream is opened
https://github.com/IBM/mini-era/blob/55293055bd5c1e7d0c523ff0192792c9b97b1a94/sim_environs.c#L105

Opened file never closed
https://github.com/IBM/mini-era/blob/55293055bd5c1e7d0c523ff0192792c9b97b1a94/sim_environs.c#L320

**Comment by jdwellman** [comment]
Corrected in commit 86a9d88
https://github.com/IBM/mini-era/commit/86a9d887f85c7202bb7c364c9424cb47adbf8978
