### ISSUE TITLE
The return value of 'sscanf()' should be checked

### ISSUE THREAD

**Issue by QiAnXinCodeSafe** [IBM/mini-era#5]
https://github.com/IBM/mini-era/blob/d280ae977d2342a9394b185e6a92b5dabf398cdd/read_trace.c#L56

**Comment by jdwellman** [comment]
This has been corrected (added checks, etc. to all *scanf type routines in main, kernel_api, read_trace and sim_environ) in this commit: https://github.com/IBM/mini-era/commit/78a3414ad084b422f51c516d08cd840b425c666f
