### ISSUE TITLE
Resource leak

### ISSUE THREAD

**Issue by QiAnXinCodeSafe** [IBM/mini-era#6]
Stream is opened
https://github.com/IBM/mini-era/blob/66e92a4f0bf4d33661a58fb0b51cf081abc836bc/kernels_api.c#L224

Opened file never closed
https://github.com/IBM/mini-era/blob/66e92a4f0bf4d33661a58fb0b51cf081abc836bc/kernels_api.c#L240

**Comment by jdwellman** [comment]
This appears (in the current master) to be a reference to the viterbi dictionary file, which is currently opened on line 226, and is closed on line 294, but is not closed when the `return error` condition is triggered.  This has been checked and corrected (added another `fclose` before the `return error`) and also for the radar dictionary.   Addressed in commit https://github.com/IBM/mini-era/commit/1631a7ddcf90e4b3a42ee46e3411b4e02ac266c6
