### ISSUE TITLE
Stream pointer might be NULL

### ISSUE THREAD

**Issue by QiAnXinCodeSafe** [IBM/mini-era#7]
'fp' is defined here, but may be NULL
https://github.com/IBM/mini-era/blob/e247a3a88affa8e0ce5ac074fdaa259bfb3b114a/fft/fft-1d/octave.c#L6

Stream pointer might be NULL
https://github.com/IBM/mini-era/blob/e247a3a88affa8e0ce5ac074fdaa259bfb3b114a/fft/fft-1d/octave.c#L9

**Comment by jdwellman** [comment]
Thank you for pointing this out; I do not believe that the "octave" export is ever used in Mini-ERA (it is a carry-over from the PERFECT Benchmarks suite from which the fft source was taken).  Still, we should clean this up.

**Comment by jdwellman** [comment]
Fixed in commit https://github.com/IBM/mini-era/commit/62b4e442d2d6976f6a3b4060c801632c909ade78
